import initAppImport from './initApp';
import initAuthImport from './initAuth';
import initCacheImport from './initCache';
import initDatabaseImport from './initDatabase';
import initEnvironmentImport from './initEnvironment';
import initLocalesImport from './initLocales';
import initModelsImport from './initModels';
import initSocketImport from './initSocket';
import initRoutesImport from './initRoutes';
import initLoggerImport from './initLogger';

export const initApp = initAppImport;
export const initAuth = initAuthImport;
export const initCache = initCacheImport;
export const initDatabase = initDatabaseImport;
export const initEnvironment = initEnvironmentImport;
export const initLocales = initLocalesImport;
export const initModels = initModelsImport;
export const initSocket = initSocketImport;
export const initRoutes = initRoutesImport;
export const initLogger = initLoggerImport;
